# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: synth
version: '0.0.0'
github: "mcxim/synth"
license: MIT
author: "Maxim Gelfand"
maintainer: ""
synopsis: Creating sounds with haskell.
# description: synth is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - process
  - bytestring
  - gloss
  # - gloss-export

  source-dirs: library

executables:
  synth:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - synth
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  synth-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - synth
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  synth-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - synth
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
